### PR TITLE
Fix start game joystick input

### LINKED ISSUE #1647: [BUG] Inputs are not available as soon as match starts
## 🐛 Bug Report
The input becomes available with a slight delay after the countdown finishes.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1647 #1635

## Motivation

When you first start the game theres is a moment when the joystick is not working but it is enable to use. 

## Summary of changes

Reduce wait time and change objects hierarchy, Also enable the buttons when their are ready.

## How has this been tested?

Start a game, in the momento the game start you should be able to use the movement joystick

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

File: client/Assets/Scripts/UI/PrepareForBattleAnimations.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ public class PrepareForBattleAnimations : MonoBehaviour
     const float PREPARE_FOR_BATTLE_DURATION = 3f;
     const float CHARACTERS_DISPLAY_DURATION = 4f;
     float TIME_UNTIL_GAME_STARTS = 0f;
-    const float SURVIVE_DURATION = 1.65f;
+    const float SURVIVE_DURATION = 1.2f;
```
Comment (agustinesco) [inline client/Assets/Scripts/UI/PrepareForBattleAnimations.cs:41]: won't this keep breaking if we want to change the prepare for battle time?

Comment (BertovDev) [reply client/Assets/Scripts/UI/PrepareForBattleAnimations.cs:41]: Yep, these whole scripts need a refactor. But it will take more time and i believe it is out of the scope of this PR.

Comment (agustinesco) [reply client/Assets/Scripts/UI/PrepareForBattleAnimations.cs:41]: yeah! i was just wondering if this was a patch or a fix. Thanks

**Review by agustinesco — APPROVED** [review]
LGTM! tested on the unity editor and in an android release in the moto g52

**Comment by AngieDutra** [comment]
Nice!I'll review now ✨

**Review by AngieDutra — APPROVED** [review]
Tested on Android build and Unity desktop. Both worked as expected
