### PR TITLE
Fix first skill execution

### LINKED ISSUE #1627: [BUG] Fix first movement skill execution
## 🐛 Bug Report

When you first execute a movement skill (Leap, dash) there is a bug where you do not move as expected.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1627 

## Motivation

We had this issue
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/d161cc6e-f7f9-4860-b006-cab2bfd724e1

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — DISMISSED** [review]
Tested on Unity desktop and Android build. Worked like a charm

**Review by agustinesco — APPROVED** [review]
LGTM!

File: client/Assets/Scripts/ClientPrediction.cs [hunk 1]
```diff
@@ -119,8 +119,7 @@ void SimulatePlayerMovement(Entity player)
             currentPosition = new Position { X = newPosition.x, Y = newPosition.z };
         });
 
-        player.Position = currentPosition;
-        player.Direction = currentDirection;
+        return player;
```
Comment (agustinesco) [inline client/Assets/Scripts/ClientPrediction.cs:122]: `currentPosition` and `currentDirection` are never added to the player like this right?

Comment (BertovDev) [reply client/Assets/Scripts/ClientPrediction.cs:126]: This seems odd, pushed a change. Nice catch.

Comment (agustinesco) [reply client/Assets/Scripts/ClientPrediction.cs:126]: hmmm this weird still, why if you weren't using these variables before the client prediction was working correctly? i think this has something to do with alising since we're doing:
```
startingPosition = player.Position;
```
then:
```
Position currentPosition = startingPosition;
```

and lastly:
```
currentPosition = new Position { X = newPosition.x, Y = newPosition.z };
```

Maybe we're changing the player position varaible directly, lets talk about this tomorrow!

File: client/Assets/Scripts/Battle.cs [hunk 2]
```diff
@@ -112,13 +112,7 @@ void Update()
...
             float clientActionRate = GameServerConnectionManager.Instance.serverTickRate_ms;
 
-            long forcedMovementMessageInterval = 500;
-            if ((nowMiliseconds - lastForcedMovementUpdate) >= forcedMovementMessageInterval)
-            {
-                SendPlayerMovement(true);
-                lastForcedMovementUpdate = nowMiliseconds;
-            }
-            else if ((nowMiliseconds - lastMovementUpdate) >= clientActionRate)
+           if ((nowMiliseconds - lastMovementUpdate) >= clientActionRate)
```
Comment (agustinesco) [inline client/Assets/Scripts/Battle.cs:115]: we'll be sending a message ever 30 ms like this right? is this correct?

**Review by agustinesco — APPROVED** [review]
LGTM! the change consist in only add movements to the client prediction if the player has made any movement or skill in the match, and always force a movement send every 30 seconds

**Review by AngieDutra — APPROVED** [review]
Tested in Android build and worked awesome!
