### PR TITLE
Fix endgame rankings and models

### LINKED ISSUE #1359: [BUG] Fix info on death splash screen
## 🐛 Bug Report

This is a bug on the main branch backend.

- model missing
- rank missing
- kills
- check for other issues

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1359 

## Motivation

Fix Death splash with new backend integration

## Summary of changes

- Fix missing model
- Fix ranking
- Refactor character creation. ( Removed repeated code)

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

File: client/Assets/Scripts/UI/EndGame/EndGameManager.cs [hunk 1]
```diff
@@ -61,22 +63,21 @@ void ShowRankingDisplay()
...
+            return WINNER_POS;
+        }
+        if (Utils.GetAlivePlayers().Count() == 0)
+        {
+            return SECOND_PLACE_POS;
+        }
+        return Utils.GetAlivePlayers().Count() + 1;
     }
 
     void ShowMatchInfo()
```
Comment (AngieDutra) [inline client/Assets/Scripts/UI/EndGame/EndGameManager.cs:83]: Here I would change the killCount value to "-". It's important we don't have hardcoded information that could be misleading or perceived as a bug

```
        // This should be un-comment once the killCount works again
        // Kill count
        //var killCount = GetKillCount();
        //amountOfKillsText.text = killCount.ToString();

        amountOfKillsText.text = "-";
```

**Review by AngieDutra — CHANGES_REQUESTED** [review]

**Review by lotuuu — APPROVED** [review]

**Review by AngieDutra — APPROVED** [review]
LGTM 🎇
