### PR TITLE
Main settings

### LINKED ISSUE #1013: [FEATURE] Settings screen (main menu and in game)
## 🚀 Feature
The settings menu can be accessed from the main menu. It includes the following sections:
#### Sound Section:
- Toggle for muting/unmuting music.
- Music volume slider.
- Toggle for muting/unmuting sound effects (SFX).
- SFX volume slider.
#### Account Section:
- Sign in: Link your account using OAuth.
- Sign out (if already logged in).

### LINKED ISSUE #1514: [BUG] Battle settings showing over death splash
## 🐛 Bug Report

It's not expected behavior to see the settings of a match that has already finish. Therefore, the bug report.

Captura de pantalla 2024-02-26 a la(s) 18 25 34

### LINKED ISSUE #1528: [FEATURE] Add go to title button in Main Settings
## 🚀 Feature

IMPORTANT issue #1013 should be done before starting this

### Motivation

A "go to title" button in settings page in Main scene. This is helpful for the user to change servers without exiting and re-entering the game

### Implementation

Make sure to check with the design team before approaching this task

Here is the drive reference:
https://drive.google.com/drive/folders/1icjh-wXViUbYebV7ixZ78CzZxH2dPVl6

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1013 
Closes #1528 
Closes #1514 

## Motivation

We didn't have a settings splash in main screen. If we had it needed a "go to title" button. Plus, there were some issues on the current setting in main.
Some issues were solved but some appeared. The sound only plays in mobile build but not in Unity desktop. AudioToggles and volume slider are not working as good as they could. A refactor is needed for this and here is an issue to tackle that  #1600 

## Summary of changes

Main:
Captura de pantalla 2024-03-25 a la(s) 5 44 48 p  m
Captura de pantalla 2024-03-25 a la(s) 5 44 43 p  m

Main:
- Server change option
- Music: mute + slider functionality
- SFX: mute + slider functionality

In Game:
Captura de pantalla 2024-03-25 a la(s) 5 50 08 p  m
Captura de pantalla 2024-03-25 a la(s) 5 50 16 p  m
Captura de pantalla 2024-03-25 a la(s) 5 50 24 p  m

In Game:
- All settings working as expected except for interpolation ghost but an issue on that is open and it wasn't working in main.
- All setting start based on the stablished config in battle.
- A refactor is needed but made this PR too complex if added in here

## How has this been tested?

Test all setting option except of those declared as not ready.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.
Captura de pantalla 2024-03-25 a la(s) 5 50 08 p  m

### CODE REVIEW

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 1]
```diff
@@ -19,24 +20,36 @@ public class ToggleAudio : MonoBehaviour
...
+    string offState = "OFF";
+    string onState = "ON";
+
     void Start()
     {
         muteButtonImage = GetComponent<Image>();
         soundManager = MMSoundManager.Instance;
         soundManager.SetTrackVolume(MMSoundManager.MMSoundManagerTracks.Master, MASTER_VOLUME);
         SetUnmutedVolume();
         soundManager.SetVolumeSfx(SFX_VOLUME);
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:44]: This is resetting the sfx volumen

We should implement the same we have for music volume but for SFX

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 2]
```diff
@@ -131,4 +148,18 @@ private bool IsMuted(MMSoundManager.MMSoundManagerTracks track)
...
+        muteButtonImage.overrideSprite = unmutedSprite;
+        textSoundState.text = onState;
+    }
+
+    private void UpdateMutedUIState()
+    {
+        muteButtonImage.enabled = mutedSprite != null;
+        muteButtonImage.overrideSprite = mutedSprite;
+        textSoundState.text = offState;
+    }
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:164]: We can simplify this with

```
    private void ToggleUIState(bool isUnMuted){
        muteButtonImage.enabled = isUnMuted;
        textSoundState.text = isUnMuted ? offState : onState;
    }
```
Also the way you are triggering this, you do not need the `unmutedSprite` and `mutedSprite` anymore

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 3]
```diff
@@ -19,24 +20,36 @@ public class ToggleAudio : MonoBehaviour
...
         soundManager.SetVolumeSfx(SFX_VOLUME);
-        muteButtonImage.overrideSprite = IsMuted(channel) ? mutedSprite : unmutedSprite;
+        if (IsMuted(channel))
+        {
+            UpdateMutedUIState();
+        }
+        else
+        {
+            UpdateUnmutedUIState();
+        }
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:52]: With the change I suggested:

```
 if (IsMuted(channel))
        {
            ToggleUIState(false);
        }
        else
        {
            ToggleUIState(true);
        }
```

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 4]
```diff
@@ -48,22 +61,29 @@ void Update()
...
             unmutedVolume = volumeSlider.value;
+            UpdateUnmutedUIState();
         }
-
-        if (volumeSlider)
+        if (volumeSlider.value == 0)
         {
-            muteButtonImage.overrideSprite =
-                volumeSlider.value == MUTED_VOLUME ? mutedSprite : unmutedSprite;
+            UpdateMutedUIState();
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:68]:
```
         ToggleUIState(true);
        }
        if (volumeSlider.value == MUTED_VOLUME)
        {
             ToggleUIState(false);
        }
```

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 5]
```diff
@@ -72,12 +92,12 @@ public void Toggle()
...
         {
             PlaySound();
-            muteButtonImage.overrideSprite = unmutedSprite;
+            UpdateUnmutedUIState();
         }
         else
         {
             SilenceSound();
-            muteButtonImage.overrideSprite = mutedSprite;
+            UpdateMutedUIState();
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:100]:
```
     if (IsMuted(channel))
        {
            PlaySound();
            ToggleUIState(true);
        }
        else
        {
            SilenceSound();
            ToggleUIState(false);
        }
```

File: client/Assets/Scripts/UI/Settings/ToggleButton.cs [hunk 6]
```diff
@@ -31,19 +35,44 @@ void Start()
             transform.parent.GetComponent<MMTouchButton>().ReturnToInitialSpriteAutomatically =
                 false;
         }
+        if (customLogs != null)
+        {
+            ToggleAllLogs();
+            ToggleCustomLogs();
+        }
+        if (battle != null)
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleButton.cs:43]: This is not working as expected, when you toggle this on, leave the game and re-enter the UI and the functionality are not matching.

**Review by BertovDev — CHANGES_REQUESTED** [review]
This is pretty well directed and minor changes have to be made. Also merge main to this.

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs (hunk 2 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/Settings/ToggleAudio.cs:164]: This was implemented as it is to have a more versatile code if two toggles are visually represented different. (In case one toggle button does have a mute sprite) But it's not the case for the current UI buttons so I could delete this until it happens 👍🏼

**Comment by AngieDutra** [comment]
All done! @BertovDev ✨

**Comment by AngieDutra** [comment]
I'll add some transparent text effects requested by @jazimp and I'll leave this ready again soon

**Comment by jazimp** [comment]
I reviewed the screenshots and functionality (from Angie's computer) and I don't see any differences from the reference! Good job 👍

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 7]
```diff
@@ -19,51 +17,89 @@ public class ToggleAudio : MonoBehaviour
...
 
+    [SerializeField]
+    TextMeshProUGUI textSoundState;
+    string offState = "OFF";
+    string onState = "ON";
+
     void Start()
     {
         muteButtonImage = GetComponent<Image>();
+        muteButtonImage.sprite = unmutedSprite;
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:38]: With this you are re-assigning the sprite by code and it is already assigned in unity. Seems not to be necessary IMO.

I will delete the unmutedSprite variable.

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 8]
```diff
@@ -19,51 +17,89 @@ public class ToggleAudio : MonoBehaviour
...
+                        currentSFXVolume != SFX_VOLUME ? currentSFXVolume : SFX_VOLUME;
+                    unmutedVolume = volumeSlider ? volumeSlider.value : sfxVolume;
+                }
+                else
+                {
+                    unmutedVolume = volumeSlider ? volumeSlider.value : SFX_VOLUME;
+                }
+                break;
         }
     }
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:104]: Simplify this creating a method single method and reusing it.

```
  private void ControlChannelTrack(MMSoundManager.MMSoundManagerTracks track, float baseVolume){
        if (!IsMuted(channel))
            {
                float currentTrackVolume = soundManager.GetTrackVolume(
                    track,
                    false
                );
                float trackVolume =
                    currentTrackVolume != baseVolume ? currentTrackVolume : baseVolume;
                unmutedVolume = volumeSlider ? volumeSlider.value : trackVolume;
            }
            else
            {
                unmutedVolume = volumeSlider ? volumeSlider.value : baseVolume;
            }
    }
```

then

   ```
 public void SetUnmutedVolume(MMSoundManager.MMSoundManagerTracks channel)
    {
        switch (channel)
        {
            case MMSoundManager.MMSoundManagerTracks.Music:
                ControlChannelTrack(channel, MUSIC_VOLUME);
                break;
            case MMSoundManager.MMSoundManagerTracks.Sfx:
                ControlChannelTrack(channel, SFX_VOLUME);
                break;
        }
    }
```

**Review by BertovDev — CHANGES_REQUESTED** [review]
Volume slider seems not to be working fine. This can be about the Update method in `VolumeController` class. Let me know if you need help to debug. 

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/c6786e6d-75d3-4eac-af46-1c3dcd99ab37

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs (hunk 7 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/Settings/ToggleAudio.cs:38]: It's easier to implement this though code in the future. Felt more implementation friendly but will delete if it doesn't make sense to apply now

**Comment by AngieDutra** [comment]
The video you sent was happening because the start value was, in main, set from the ui implementation. To avoid this issue, now and in the future, I set this value from the code

**Comment by saugon** [comment]
I have a small request. Could the active tab default to the first one every time the settings are opened? For example, if I open the settings from the main screen, switch to the server tab, and then close it, the next time I open it, the server tab is still active

**Comment by AngieDutra** [comment]
I could make this addition work in regards the tabs but could quickly reset the scroll position

**Review by BertovDev — DISMISSED** [review]
Awesome work

File: client/Assets/Scripts/UI/Settings/ToggleAudio.cs [hunk 9]
```diff
@@ -19,51 +14,76 @@ public class ToggleAudio : MonoBehaviour
...
     void Start()
     {
         muteButtonImage = GetComponent<Image>();
         soundManager = MMSoundManager.Instance;
         soundManager.SetTrackVolume(MMSoundManager.MMSoundManagerTracks.Master, MASTER_VOLUME);
-        SetUnmutedVolume();
-        soundManager.SetVolumeSfx(SFX_VOLUME);
-        muteButtonImage.overrideSprite = IsMuted(channel) ? mutedSprite : unmutedSprite;
+        SetUnmutedVolume(channel);
+        if (IsMuted(channel))
```
Comment (saugon) [inline client/Assets/Scripts/UI/Settings/ToggleAudio.cs:38]: This If statement (and several others in this PR) could be simplified with something like:

`ToggleUIState(!IsMuted(channel));`

Or, for better readability:
```
toggleValue = !IsMuted(channel);
ToggleUIState(toggleValue);
```

**Comment by AngieDutra** [comment]
Okey. I'll push this change and a fix to the toggle problem @BertovDev mentioned. (Starting the match with muted music and being able to toggle it in game)

**Review by BertovDev — DISMISSED** [review]
Really nice

**Comment by AngieDutra** [comment]
Just tested in Android build and in Unity build ✨

**Review by saugon — APPROVED** [review]
Great job!

**Review by BertovDev — APPROVED** [review]
